name: Ranks 
author: DevilDev 
version: 1.0.0 
api: 4.0.0 
main: rank\Ranks 

commands: 
  rank:
    discription: "Add Rank For A Player"
    permission: sroudy.rank 

permissions: 
  sroudy.rank: 
    discription: SroudyNetwork Rank Permission
    default: op